### ISSUE TITLE
Unable to `sudo` anything while logged in as AAD user

### ISSUE THREAD

**Issue by johnkattenhorn** [ubuntu/aad-auth#197]
Description / Steps to Re-produce:

1) Login in using an AAD account (I'm a global admin)
2) Open Terminal Windows
3) Try to use `sudo`, for example `sudo pro attach [key]`
4) Type in account password when requested

Always returns: Sorry, try again

My password is correct (it does have Upper, Lower and Symbols in it)

My local account (which has the same password), works if I switch users etc.

**Comment by kirkog86** [comment]
Same here...
usermod -aG sudo <user@domain.com> do nothing...

Tried to add user to /etc/passwd and to /etc/group, same-same.

Does sudo group assignment should come from AAD....?

**Comment by didrocks** [comment]
Thanks for reporting this bug and help making aad-auth better. This is indeed a bug, we expect at least manual usermod to add to a local group to work (no support yet from global admin in azure AD to local administrator).

We will investigate it and work on fixing the `usermod` case.

**Comment by franck-iaropoli-arm** [comment]
Thanks for having a look to this issue @didrocks.
I am seeing below message after enabling logging
` can not create/open cache for nss database: failed to update user "user@domain.com" in local cache: shadow database is
 not accessible for writing: 0. Denying access.  `

For now I setup a sudo role without password for my AAD account (being a member of the sudo group doesn't help).
I created /etc/sudoers.d/user file with below content:
`user@domain.com  ALL=(ALL) NOPASSWD: ALL`

**Comment by velayudhamv** [comment]
Even I am seeing the same issue. Can’t use AAD credentials to sudo.
Tried usermod and still same issue. Tried creating 
 /etc/sudoers.d/user file with below content:
user@domain.com  ALL=(ALL: ALL) ALL
Still not able to sudo after restart too.

**Comment by dzejzipl** [comment]
Uh. I think it's big gap of security... Using sudo without password..
Not really good :/

**Comment by turowicz** [comment]
Problem still here - what do we do to solve it?

**Comment by dzejzipl** [comment]
> 

I tested it and the solution was to install packages from 
https://launchpad.net/~justdenis/+archive/ubuntu/test-aad-auth

**Comment by turowicz** [comment]
404 Not Found

**Comment by michael-staffa** [comment]
@turowicz I believe they moved the temporary fix to a different PPA as mentioned in this comment:
https://github.com/ubuntu/aad-auth/pull/215#issuecomment-1597380298
