### ISSUE TITLE
packages not found

### ISSUE THREAD

**Issue by AllDeesScripts** [ubuntu/aad-auth#198]
When running **sudo apt install libpam-aad libnss-aad** I get package not found for both of them. 

When I run apt update and check the apt cache it's definitely not got the two packages listed. I see that the Ubunto Pro subscription is required for the overall solution to work. Is it required for me to even see the packages in the universe repository?

**Comment by kirkog86** [comment]
Are you doing apt from 23.04?
Out of the box, it's available only on Lunar Lobster.
Canonical promised to backport aad-auth to LTS versions later on.

**Comment by AllDeesScripts** [comment]
ahhh thank you, thank VM is 22.04. Just building 23.04 now for testing. Will close the issue if this resolves it. 

Thanks again 👍

**Comment by jibel** [comment]
Thanks for reporting this issue. I'm closing it since it is not a bug. Feel free to reopen if you have problems installing the module in 23.04.

Do not hesitate to report any issue you may find.

**Comment by AllDeesScripts** [comment]
I can confirm this was due to not being on 23.04.
