### ISSUE TITLE
Add aad-auth during OS provisioning 

### ISSUE THREAD

**Issue by kirkog86** [ubuntu/aad-auth#199]
The new Ubuntu installer looks sharp!
However, adding aad-auth DURING the installation of the OS will make the process much more streamlined.

**Comment by didrocks** [comment]
Thanks for your interest on aad-auth! We are definitively considering the installer and os provisionning part for the next ubuntu LTS release. As the installer is not part of this project I am closing it here, but feel free to track the work on the ubuntu installer project (https://github.com/canonical/ubuntu-desktop-installer).
