### ISSUE TITLE
Sudo execution

### ISSUE THREAD

**Issue by idaaas22** [ubuntu/aad-auth#235]
Hello,

From side, with aad-auth module installed:
- I can login localy (console) with my O365 account
- MFA is not requested (a bug is already open)
- I can login with ssh (after adding "auth [success=1 default=ignore] pam_aad.so" in /etc/pam.d/sshd file)
- BUT I can't execute sudo command. It's like the password is always wrong. password Cache is disabled. I have added  "auth [success=1 default=ignore] pam_aad.so" in /etc/pam.d/sudo and sudo-i files. The problem can come from misconfiguration. User in member of sudo group
Do you have an explain for this issue ?
Regards

20230529:
I have re-enabled cache by changing in aad.conf file offline_credentials_expiration from -1 to 2. Computer rebooted.
Here are my logfiles
May 29 09:44:38 ubuntu sudo[1030]: pam_aad(sudo:auth): aad auth debug enabled
May 29 09:44:38 ubuntu sudo[1030]: pam_aad(sudo:auth): PAM AAD DEBUG enabled
May 29 09:44:38 ubuntu sudo[1030]: pam_aad(sudo:auth): Loading configuration from /etc/aad.conf
May 29 09:44:38 ubuntu sudo[1030]: pam_aad(sudo:auth): Connecting to "https://login.microsoftonline.com/XXXXXXXXXXXX", with clientID "XXXX>
May 29 09:44:39 ubuntu sudo[1030]: pam_aad(sudo:auth): Authentication successful even if requiring MFA
May 29 09:44:39 ubuntu sudo[1030]: pam_aad(sudo:auth): Reusing existing opened cache
May 29 09:44:39 ubuntu sudo[1030]: pam_aad(sudo:auth): getting user information from cache for "myuser@mydomain"
May 29 09:44:39 ubuntu sudo[1030]: pam_aad(sudo:auth): encrypt password for user "myuser@mydomain"
May 29 09:44:39 ubuntu sudo[1030]: pam_aad(sudo:auth): updating from last online login information for user "myuser@mydomain"
May 29 09:44:39 ubuntu sudo[1030]: pam_aad(sudo:auth): can not create/open cache for nss database: failed to update user "myuser@mydomain" in local cache: shadow database>
May 29 09:44:39 ubuntu sudo[1030]: pam_aad(sudo:auth): Close database request
May 29 09:44:41 ubuntu aad_auth[1030]: nss_aad: get_entry_by_name for passwd for name: myuser@mydomain
May 29 09:44:41 ubuntu aad_auth[1030]: nss_aad: opening database connection from /var/lib/aad/cache
May 29 09:44:41 ubuntu aad_auth[1030]: nss_aad: Checking file "/var/lib/aad/cache/passwd.db" permissions
May 29 09:44:41 ubuntu aad_auth[1030]: nss_aad: Checking file "/var/lib/aad/cache/shadow.db" permissions
May 29 09:44:41 ubuntu aad_auth[1030]: nss_aad: found record: Passwd { name: "myuser@mydomain", passwd: "x", uid: 3901916832, gid: 3901916832, gecos: "", home: "/home/myu>
May 29 09:44:41 ubuntu aad_auth[1030]: nss_aad: get_entry_by_name for shadow for name: myuser@mydomain
May 29 09:44:41 ubuntu aad_auth[1030]: nss_aad: opening database connection from /var/lib/aad/cache
May 29 09:44:41 ubuntu aad_auth[1030]: nss_aad: Checking file "/var/lib/aad/cache/passwd.db" permissions
May 29 09:44:41 ubuntu aad_auth[1030]: nss_aad: Checking file "/var/lib/aad/cache/shadow.db" permissions
May 29 09:44:41 ubuntu aad_auth[1030]: nss_aad: found record: Shadow { name: "myuser@mydomain", passwd: "REDACTED", last_pwd_change: -1, min_pwd_age: -1, max_pwd_age: -1,>
May 29 09:44:41 ubuntu aad_auth[1030]: nss_aad: get_entry_by_name for passwd for name: pam_unix_non_existent:
May 29 09:44:41 ubuntu aad_auth[1030]: nss_aad: opening database connection from /var/lib/aad/cache
May 29 09:44:41 ubuntu aad_auth[1030]: nss_aad: Checking file "/var/lib/aad/cache/passwd.db" permissions
May 29 09:44:41 ubuntu aad_auth[1030]: nss_aad: Checking file "/var/lib/aad/cache/shadow.db" permissions
May 29 09:44:41 ubuntu aad_auth[1030]: nss_aad: no record found
May 29 09:44:42 ubuntu sudo[1030]: pam_unix(sudo:auth): conversation failed
May 29 09:44:42 ubuntu sudo[1030]: pam_unix(sudo:auth): auth could not identify password for [myuser@mydomain]
May 29 09:44:42 ubuntu sudo[1030]: pam_aad(sudo:auth): aad auth debug enabled
May 29 09:44:42 ubuntu sudo[1030]: pam_aad(sudo:auth): PAM AAD DEBUG enabled
May 29 09:44:42 ubuntu sudo[1030]: pam_aad(sudo:auth): no password found
May 29 09:44:42 ubuntu sudo[1030]: myuser@mydomain : 2 incorrect password attempts ; TTY=pts/0 ; PWD=/home/myuser@mydomain ; USER=root ; COMMAND=/usr/bin/whoami

NSS database seems to be unable to be updated

**Comment by denisonbarbosa** [comment]
Hey @idaaas22! Thanks for reporting the issue and helping improve `aad-auth`. This issue looks very similar to #197, which was fixed, but not released on the archive yet. Would you mind testing the version available in the PPA (linked in the pull request #215) and then reporting back on this issue?

**Comment by idaaas22** [comment]
Hey @denisonbarbosa , I have installed the PPA and sudo commands works now.
When the PPA will be officially supported ?
Thank you

**Comment by denisonbarbosa** [comment]
I'm glad it works! Since this is resolved, I'll close this issue.
We are still handling a couple of things before releasing a new version, but when it happens you will be able to see the new release listed in the `releases` section on github.

**Comment by turowicz** [comment]
PPA is gone, sudo doesn't work

**Comment by turowicz** [comment]
@denisonbarbosa thank you for the reply. Is there a reasony why its in a separate ppa rather than just in the main package?
