### ISSUE TITLE
Question: Is home folder synchronised to cloud?

### ISSUE THREAD

**Issue by turowicz** [ubuntu/aad-auth#258]
It is on Windows by default. Would be nice to have it also do that on Linux (dotfolders, dotfiles, Documents etc)

**Comment by denisonbarbosa** [comment]
Hey @turowicz! Sadly, it isn't.  `aad-auth` only handles the authentication and some user configuration like home directory and shell.

**Comment by turowicz** [comment]
That would be a Pro feature worth it's price.
