### ISSUE TITLE
Question: Is Ubuntu Pro subscription required to use the login feature?

### ISSUE THREAD

**Issue by turowicz** [ubuntu/aad-auth#259]
Managing Ubuntu machines (servers esp.) is very useful. Do we have to pay for the Pro license to be able to do it?

**Comment by denisonbarbosa** [comment]
Hey, @turowicz! You don't need a Pro subscription to be able to use the package.

**Comment by denisonbarbosa** [comment]
Pro will be required in the next LTS release, but it isn't required for now.
