### ISSUE TITLE
Changed password in Azure AD does not work locally

### ISSUE THREAD

**Issue by turowicz** [ubuntu/aad-auth#267]
After changing the password through the https://account.activedirectory.windowsazure.com/r/#/profile portal I am unable to login to the Ubuntu machine with the new password. The computer is on internet access via Ethernet cable 1Gbps.

**Comment by turowicz** [comment]
@denisonbarbosa I am currently unable to log in because after installing your PPA the scope is invalid for login as per this issue:

https://github.com/ubuntu/aad-auth/issues/256

**Comment by denisonbarbosa** [comment]
Which version of `aad-auth` are you currently running? I updated the PPA yesterday and the version should be `0.4.1~ppa2`, you can check it by running `aad-cli version`.

**Comment by turowicz** [comment]
I have the update, let me try.

**Comment by turowicz** [comment]
![image](https://github.com/ubuntu/aad-auth/assets/1055391/2b2611ad-9f48-465f-b859-252dfaf92365)

**Comment by turowicz** [comment]
I have managed to login after password change in the cloud on the recent version.
