### ISSUE TITLE
journalctl?

### ISSUE THREAD

**Issue by turowicz** [ubuntu/aad-auth#268]
The documentation mentions `journalctl` but it doesn't say what module name to use in the `-u` parameter for better readibility.

**Comment by turowicz** [comment]
so far I go with `journalctl | grep pam_aad`

**Comment by denisonbarbosa** [comment]
Hey @turowicz. The `-u` option is for filtering `journalctl` output by `systemd` units, but the logs for `aad-auth` are all through the user@{uid}.service, so using it won't help you filter the logs that you want. So the best way of doing it is through:
```bash
# for the nss logs
journalctl | grep nss_aad 

# for the pam logs
journalctl | grep pam_aad

# for both
journalctl | grep _aad
```

**Comment by turowicz** [comment]
thanks!
