### ISSUE TITLE
Can not add aad user to sudoers

### ISSUE THREAD

**Issue by nayodahl** [ubuntu/aad-auth#270]
## Description

I'm unable to give sudoers rights to a aad account.

## Reproduction

I have sucessfully added a aad account that is authenticating against my aad.
Now I would like to give sudoers rights to this account, to give him local admin privileges when needed.

I have added an entry in /etc/sudoers.d/aad_admins with correct permissions : 
`userexemple@domain.com   ALL=(ALL:ALL) ALL
` 
The command `visudo -c` tells me the sudo configuration is ok : 
```
/etc/sudoers: parsed OK
/etc/sudoers.d/README: parsed OK
/etc/sudoers.d/aad_admins: parsed OK
```

But when trying to get sudo rights, I'm receiving password error : Sorry, try again.

In /var/log/auth.log : 
```
sudo; pam_unix(sudo:auth): authentication failure; logname= uid=XXXXX euid=0 tty=/dev/pts/4 ruser=userexemple@domain.com rhost= user=userexemple@domain.com
sudo: pam_aad(sudo:auth): can not create/open cache for nss database: failed to update user "userexemple@domain.com" in local cache:shadow database is not accessible for writing: 0. Denying access.
```

### Environment

Ubuntu latest

**Comment by denisonbarbosa** [comment]
Hey @nayodahl. This issue was already fixed by #215, but it's not officially released to the archive yet.
