### ISSUE TITLE
Ability to sudo

### ISSUE THREAD

**Issue by nopa6** [ubuntu/aad-auth#348]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

I am able to log in as a user without issue, but am unable to execute sudo. Although I get the sudo instruction when opening a new terminal, the password fails every time. There are a few related issues to this, such as #236  but nothing this specific.

Manually adding the suer to the sudo group does not resolve.

Manually adding the user to `/etc/sudoers` does not resolve. (Special care taken to escape the @ symbol in user name.)

Many, many, reboot and login/logout cycles later with other tweaks and I am at a loss. Any advice appreciated.

### Steps to reproduce it

Shell:

```
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

first.last@domain.com@ubuntu:~$ sudo whoami
[sudo] password for first.last@domain.com: 
Sorry, try again.
[sudo] password for first.last@domain.com: 
```

**Comment by denisonbarbosa** [comment]
Hey @nopa6, this issue was already fixed by #215. It will be available on `aad-auth 0.5.2`, which will be released on 23.10.
